% exercise 5.1.6

% Fit classification tree
T = fitctree(X, classNames(y+1), ...    
    'splitcriterion', 'gdi', ...
    'categorical', [], ...
    'PredictorNames', attributeNames, ...
    'prune', 'on', ...
    'minparent', 50);

% View the tree
view(T, 'Mode','graph')
